[plugin]
name = "bridge"
version = "0.1.0"
description = "Forward messages between QQ and Telegram platforms, like a switch"
authors = ["Vollate"]
license = "MIT"

[dependencies]
required_plugins = []

[build]
vcpkg_deps = ["sqlite3", "tomlplusplus"]
